# Generated by Django 4.2.3 on 2023-07-10 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='default.jpg', upload_to='media', verbose_name='Фото')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('ingredients', models.TextField(default='', verbose_name='Ингридиенты')),
                ('recipe', models.TextField(default='', verbose_name='Рецепт')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.category', verbose_name='Категория')),
            ],
        ),
    ]
